// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --replace-value-regex "__omp_offloading_[0-9a-z]+_[0-9a-z]+(\w+)_l[0-9]+" "reduction_size[.].+[.]" "pl_cond[.].+[.|,]" --prefix-filecheck-ir-name _ --version 6
// expected-no-diagnostics
#ifndef HEADER
#define HEADER

///==========================================================================///
// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2

// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2

// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-64,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18
// RUN: %clang_cc1 -DCK31 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2
// RUN: %clang_cc1 -DCK31 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK,CK31,CK31-32,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2

// RUN: %clang_cc1 -DCK31 -verify -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18,SIMD-ONLY18 %s
// RUN: %clang_cc1 -DCK31 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18,SIMD-ONLY18 %s
// RUN: %clang_cc1 -DCK31 -verify -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18,SIMD-ONLY18 %s
// RUN: %clang_cc1 -DCK31 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK,CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18,CK31-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY18-_2,SIMD-ONLY18 %s
#ifdef CK31



void explicit_maps_single (int ii){
  // Map of a scalar.
  int a = ii;

// Close.
// Region 00


#pragma omp target map(close, tofrom \
                       : a)
  {
   a++;
  }

// Always Close.
// Region 01


#pragma omp target map(always close tofrom \
                       : a)
  {
   a++;
  }
}

#endif // CK31
#endif
// CHECK-CK-LABEL: define dso_local void @_Z20explicit_maps_singlei(
// CK31-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY18-SAME: i32 noundef signext [[II:%.*]]) #[[ATTR0:[0-9]+]] {
// CK31-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY18-SAME: i32 noundef [[II:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-CK-NEXT:  [[ENTRY:.*:]]
// CHECK-CK-NEXT:    [[II_ADDR:%.*]] = alloca i32, align 4
// CHECK-CK-NEXT:    [[A:%.*]] = alloca i32, align 4
// CK31-64-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 8
// CK31-64-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 8
// CK31-64-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 8
// CK31-32-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 4
// CK31-32-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 4
// CK31-32-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 4
// CK31-NEXT:    [[KERNEL_ARGS:%.*]] = alloca [[STRUCT___TGT_KERNEL_ARGUMENTS:%.*]], align 8
// CK31-64-NEXT:    [[DOTOFFLOAD_BASEPTRS1:%.*]] = alloca [1 x ptr], align 8
// CK31-64-NEXT:    [[DOTOFFLOAD_PTRS2:%.*]] = alloca [1 x ptr], align 8
// CK31-64-NEXT:    [[DOTOFFLOAD_MAPPERS3:%.*]] = alloca [1 x ptr], align 8
// CK31-32-NEXT:    [[DOTOFFLOAD_BASEPTRS1:%.*]] = alloca [1 x ptr], align 4
// CK31-32-NEXT:    [[DOTOFFLOAD_PTRS2:%.*]] = alloca [1 x ptr], align 4
// CK31-32-NEXT:    [[DOTOFFLOAD_MAPPERS3:%.*]] = alloca [1 x ptr], align 4
// CK31-NEXT:    [[KERNEL_ARGS4:%.*]] = alloca [[STRUCT___TGT_KERNEL_ARGUMENTS]], align 8
// CHECK-CK-NEXT:    store i32 [[II]], ptr [[II_ADDR]], align 4
// CHECK-CK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[II_ADDR]], align 4
// CHECK-CK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
// SIMD-ONLY18-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A]], align 4
// SIMD-ONLY18-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP1]], 1
// SIMD-ONLY18-NEXT:    store i32 [[INC]], ptr [[A]], align 4
// SIMD-ONLY18-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A]], align 4
// SIMD-ONLY18-NEXT:    [[INC1:%.*]] = add nsw i32 [[TMP2]], 1
// SIMD-ONLY18-NEXT:    store i32 [[INC1]], ptr [[A]], align 4
// CK31-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS]], i32 0, i32 0
// CK31-64-NEXT:    store ptr [[A]], ptr [[TMP1]], align 8
// CK31-32-NEXT:    store ptr [[A]], ptr [[TMP1]], align 4
// CK31-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS]], i32 0, i32 0
// CK31-64-NEXT:    store ptr [[A]], ptr [[TMP2]], align 8
// CK31-64-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i64 0, i64 0
// CK31-64-NEXT:    store ptr null, ptr [[TMP3]], align 8
// CK31-32-NEXT:    store ptr [[A]], ptr [[TMP2]], align 4
// CK31-32-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i32 0, i32 0
// CK31-32-NEXT:    store ptr null, ptr [[TMP3]], align 4
// CK31-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 0
// CK31-NEXT:    store i32 3, ptr [[TMP4]], align 4
// CK31-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 1
// CK31-NEXT:    store i32 1, ptr [[TMP5]], align 4
// CK31-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 2
// CK31-64-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS]], ptr [[TMP6]], align 8
// CK31-32-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS]], ptr [[TMP6]], align 4
// CK31-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 3
// CK31-64-NEXT:    store ptr [[DOTOFFLOAD_PTRS]], ptr [[TMP7]], align 8
// CK31-32-NEXT:    store ptr [[DOTOFFLOAD_PTRS]], ptr [[TMP7]], align 4
// CK31-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 4
// CK31-64-NEXT:    store ptr @.offload_sizes, ptr [[TMP8]], align 8
// CK31-32-NEXT:    store ptr @.offload_sizes, ptr [[TMP8]], align 4
// CK31-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 5
// CK31-64-NEXT:    store ptr @.offload_maptypes, ptr [[TMP9]], align 8
// CK31-32-NEXT:    store ptr @.offload_maptypes, ptr [[TMP9]], align 4
// CK31-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 6
// CK31-64-NEXT:    store ptr null, ptr [[TMP10]], align 8
// CK31-32-NEXT:    store ptr null, ptr [[TMP10]], align 4
// CK31-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 7
// CK31-64-NEXT:    store ptr null, ptr [[TMP11]], align 8
// CK31-32-NEXT:    store ptr null, ptr [[TMP11]], align 4
// CK31-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 8
// CK31-NEXT:    store i64 0, ptr [[TMP12]], align 8
// CK31-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 9
// CK31-NEXT:    store i64 0, ptr [[TMP13]], align 8
// CK31-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 10
// CK31-NEXT:    store [3 x i32] [i32 -1, i32 0, i32 0], ptr [[TMP14]], align 4
// CK31-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 11
// CK31-NEXT:    store [3 x i32] zeroinitializer, ptr [[TMP15]], align 4
// CK31-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 12
// CK31-NEXT:    store i32 0, ptr [[TMP16]], align 4
// CK31-NEXT:    [[TMP17:%.*]] = call i32 @__tgt_target_kernel(ptr @[[GLOB1:[0-9]+]], i64 -1, i32 -1, i32 0, ptr @.{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z20explicit_maps_singlei_l[0-9]+}}.region_id, ptr [[KERNEL_ARGS]])
// CK31-NEXT:    [[TMP18:%.*]] = icmp ne i32 [[TMP17]], 0
// CK31-NEXT:    br i1 [[TMP18]], label %[[OMP_OFFLOAD_FAILED:.*]], label %[[OMP_OFFLOAD_CONT:.*]]
// CK31:       [[OMP_OFFLOAD_FAILED]]:
// CK31-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z20explicit_maps_singlei_l[0-9]+}}(ptr [[A]]) #[[ATTR2:[0-9]+]]
// CK31-NEXT:    br label %[[OMP_OFFLOAD_CONT]]
// CK31:       [[OMP_OFFLOAD_CONT]]:
// CK31-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS1]], i32 0, i32 0
// CK31-64-NEXT:    store ptr [[A]], ptr [[TMP19]], align 8
// CK31-32-NEXT:    store ptr [[A]], ptr [[TMP19]], align 4
// CK31-NEXT:    [[TMP20:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS2]], i32 0, i32 0
// CK31-64-NEXT:    store ptr [[A]], ptr [[TMP20]], align 8
// CK31-64-NEXT:    [[TMP21:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS3]], i64 0, i64 0
// CK31-64-NEXT:    store ptr null, ptr [[TMP21]], align 8
// CK31-32-NEXT:    store ptr [[A]], ptr [[TMP20]], align 4
// CK31-32-NEXT:    [[TMP21:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS3]], i32 0, i32 0
// CK31-32-NEXT:    store ptr null, ptr [[TMP21]], align 4
// CK31-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 0
// CK31-NEXT:    store i32 3, ptr [[TMP22]], align 4
// CK31-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 1
// CK31-NEXT:    store i32 1, ptr [[TMP23]], align 4
// CK31-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 2
// CK31-64-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS1]], ptr [[TMP24]], align 8
// CK31-32-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS1]], ptr [[TMP24]], align 4
// CK31-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 3
// CK31-64-NEXT:    store ptr [[DOTOFFLOAD_PTRS2]], ptr [[TMP25]], align 8
// CK31-32-NEXT:    store ptr [[DOTOFFLOAD_PTRS2]], ptr [[TMP25]], align 4
// CK31-NEXT:    [[TMP26:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 4
// CK31-64-NEXT:    store ptr @.offload_sizes.1, ptr [[TMP26]], align 8
// CK31-32-NEXT:    store ptr @.offload_sizes.1, ptr [[TMP26]], align 4
// CK31-NEXT:    [[TMP27:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 5
// CK31-64-NEXT:    store ptr @.offload_maptypes.2, ptr [[TMP27]], align 8
// CK31-32-NEXT:    store ptr @.offload_maptypes.2, ptr [[TMP27]], align 4
// CK31-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 6
// CK31-64-NEXT:    store ptr null, ptr [[TMP28]], align 8
// CK31-32-NEXT:    store ptr null, ptr [[TMP28]], align 4
// CK31-NEXT:    [[TMP29:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 7
// CK31-64-NEXT:    store ptr null, ptr [[TMP29]], align 8
// CK31-32-NEXT:    store ptr null, ptr [[TMP29]], align 4
// CK31-NEXT:    [[TMP30:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 8
// CK31-NEXT:    store i64 0, ptr [[TMP30]], align 8
// CK31-NEXT:    [[TMP31:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 9
// CK31-NEXT:    store i64 0, ptr [[TMP31]], align 8
// CK31-NEXT:    [[TMP32:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 10
// CK31-NEXT:    store [3 x i32] [i32 -1, i32 0, i32 0], ptr [[TMP32]], align 4
// CK31-NEXT:    [[TMP33:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 11
// CK31-NEXT:    store [3 x i32] zeroinitializer, ptr [[TMP33]], align 4
// CK31-NEXT:    [[TMP34:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS4]], i32 0, i32 12
// CK31-NEXT:    store i32 0, ptr [[TMP34]], align 4
// CK31-NEXT:    [[TMP35:%.*]] = call i32 @__tgt_target_kernel(ptr @[[GLOB1]], i64 -1, i32 -1, i32 0, ptr @.{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z20explicit_maps_singlei_l[0-9]+}}.region_id, ptr [[KERNEL_ARGS4]])
// CK31-NEXT:    [[TMP36:%.*]] = icmp ne i32 [[TMP35]], 0
// CK31-NEXT:    br i1 [[TMP36]], label %[[OMP_OFFLOAD_FAILED5:.*]], label %[[OMP_OFFLOAD_CONT6:.*]]
// CK31:       [[OMP_OFFLOAD_FAILED5]]:
// CK31-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z20explicit_maps_singlei_l[0-9]+}}(ptr [[A]]) #[[ATTR2]]
// CK31-NEXT:    br label %[[OMP_OFFLOAD_CONT6]]
// CK31:       [[OMP_OFFLOAD_CONT6]]:
// CHECK-CK-NEXT:    ret void
//
//
// CK31-LABEL: define internal void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z20explicit_maps_singlei_l[0-9]+}}(
// CK31-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[A:%.*]]) #[[ATTR1:[0-9]+]] {
// CK31-NEXT:  [[ENTRY:.*:]]
// CK31-64-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CK31-64-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CK31-64-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8, !nonnull [[META7:![0-9]+]], !align [[META8:![0-9]+]]
// CK31-32-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 4
// CK31-32-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 4
// CK31-32-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 4, !nonnull [[META8:![0-9]+]], !align [[META9:![0-9]+]]
// CK31-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4
// CK31-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP1]], 1
// CK31-NEXT:    store i32 [[INC]], ptr [[TMP0]], align 4
// CK31-NEXT:    ret void
//
//
// CK31-64: [[META7]] = !{}
// CK31-64: [[META8]] = !{i64 4}
// CK31-32: [[META8]] = !{}
// CK31-32: [[META9]] = !{i64 4}
//.
