// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --replace-value-regex "__omp_offloading_[0-9a-z]+_[0-9a-z]+(\w+)_l[0-9]+" "reduction_size[.].+[.]" "pl_cond[.].+[.|,]" --prefix-filecheck-ir-name _ --version 6
// expected-no-diagnostics
#ifndef HEADER
#define HEADER

///==========================================================================///
// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22

// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22

// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK,CK23,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22

// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22 %s
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22 %s
// RUN: %clang_cc1 -std=c++11 -DCK23 -verify -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22,CK23-64-_7-_4-32-_2-_5-_6-_3-SIMD-ONLY22 %s
// RUN: %clang_cc1 -std=c++11 -DCK23 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -std=c++11 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK,CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22 %s
#ifdef CK23







int explicit_maps_inside_captured(int a){
  float b;
  float c[100];
  float *d;

  [&](void){
// Region 00


#pragma omp target map(a)
      { a+=1; }
// Region 01


#pragma omp target map(b)
      { b+=1; }
// Region 02


#pragma omp target map(c)
      { c[3]+=1; }

// Region 03


#pragma omp target map(d)
      { d[3]+=1; }
// Region 04


#pragma omp target map(c [2:4])
      { c[3]+=1; }

// Region 05

//  &d[0], &d[2], 4 * sizeof(d[0]), TO | FROM
//  &d,    &d[2], sizeof(d),        ATTACH



#pragma omp target map(d [2:4])
      { d[3]+=1; }
  }();
  return b;
}

#endif // CK23
#endif
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-LABEL: define dso_local noundef signext i32 @_Z29explicit_maps_inside_capturedi(
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-SAME: i32 noundef signext [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-LABEL: define dso_local noundef i32 @_Z29explicit_maps_inside_capturedi(
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-SAME: i32 noundef [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[C:%.*]] = alloca [100 x float], align 4
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    [[D:%.*]] = alloca ptr, align 8
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    [[REF_TMP:%.*]] = alloca [[CLASS_ANON:%.*]], align 8
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    [[D:%.*]] = alloca ptr, align 4
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    [[REF_TMP:%.*]] = alloca [[CLASS_ANON:%.*]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw [[CLASS_ANON]], ptr [[REF_TMP]], i32 0, i32 0
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    store ptr [[A_ADDR]], ptr [[TMP0]], align 8
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    store ptr [[A_ADDR]], ptr [[TMP0]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw [[CLASS_ANON]], ptr [[REF_TMP]], i32 0, i32 1
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    store ptr [[B]], ptr [[TMP1]], align 8
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    store ptr [[B]], ptr [[TMP1]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw [[CLASS_ANON]], ptr [[REF_TMP]], i32 0, i32 2
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    store ptr [[C]], ptr [[TMP2]], align 8
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    store ptr [[C]], ptr [[TMP2]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [[CLASS_ANON]], ptr [[REF_TMP]], i32 0, i32 3
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    store ptr [[D]], ptr [[TMP3]], align 8
// CK23-64-_7-_4-_6-_5-_3-_2-SIMD-ONLY22-NEXT:    call void @"_ZZ29explicit_maps_inside_capturediENK3$_0clEv"(ptr noundef nonnull align 8 dereferenceable(32) [[REF_TMP]])
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    store ptr [[D]], ptr [[TMP3]], align 4
// CK23-32-_2-_5-_7-_4-_6-_3-SIMD-ONLY22-NEXT:    call void @"_ZZ29explicit_maps_inside_capturediENK3$_0clEv"(ptr noundef nonnull align 4 dereferenceable(16) [[REF_TMP]])
// CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[B]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = fptosi float [[TMP4]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
//
//
