// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --replace-value-regex "__omp_offloading_[0-9a-z]+_[0-9a-z]+(\w+)_l[0-9]+" "reduction_size[.].+[.]" "pl_cond[.].+[.|,]" --prefix-filecheck-ir-name _ --version 6
// RUN: %clang_cc1 -verify -Wno-vla -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck %s --check-prefixes=CHECK-CK,CK1,CK1-64,CK1-64-_3-_2-32-SIMD-ONLY0,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify -Wno-vla %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK-CK,CK1,CK1-64,CK1-64-_3-_2-32-SIMD-ONLY0,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2
// RUN: %clang_cc1 -verify -Wno-vla -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck %s --check-prefixes=CHECK-CK,CK1,CK1-32,CK1-32-_2-_3-SIMD-ONLY0,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2,CK1-64-_3-_2-32-SIMD-ONLY0,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify -Wno-vla %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK-CK,CK1,CK1-32,CK1-32-_2-_3-SIMD-ONLY0,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2,CK1-64-_3-_2-32-SIMD-ONLY0,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4

// RUN: %clang_cc1 -verify -Wno-vla -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK-CK,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2,SIMD-ONLY0,SIMD-ONLY0-_5-_4 %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify -Wno-vla %s -emit-llvm -o - | FileCheck --check-prefixes=CHECK-CK,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2,SIMD-ONLY0,SIMD-ONLY0-_5-_4 %s
// RUN: %clang_cc1 -verify -Wno-vla -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK-CK,CK1-32-_2-_3-SIMD-ONLY0,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-32-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,SIMD-ONLY0,SIMD-ONLY0-_3-_2 %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify -Wno-vla %s -emit-llvm -o - | FileCheck --check-prefixes=CHECK-CK,CK1-32-_2-_3-SIMD-ONLY0,CK1-32-_2-_3-SIMD-ONLY0-_5-_4,CK1-64-_3-_2-32-SIMD-ONLY0,CK1-64-_3-_2-SIMD-ONLY0-_5-_4,SIMD-ONLY0,SIMD-ONLY0-_3-_2 %s

// expected-no-diagnostics
#ifndef HEADER
#define HEADER

template <typename T>
struct ST {
  T a;
  double *b;
};

ST<int> gb;
double gc[100];





void foo(int arg) {
  int la;
  float lb[arg];


  // Region 00

  #pragma omp target exit data if(1+3-5) device(arg) map(from:gc) nowait depend(in: arg)
  {++arg;}

  // Region 01
  #pragma omp target exit data map(release: la) if(1+3-4) depend(in: la) depend(out: arg)
  {++arg;}

  // Region 02


  #pragma omp target exit data map(delete: arg) if(arg) device(4) depend(inout: arg, la, gc)
  {++arg;}

  {++arg;}

  // Region 03
  #pragma omp target exit data map(from:lb) depend(out: lb, arg, la, gc)
  {++arg;}

  {++arg;}

  // Region 04

  // &gb.b[0], &gb.b[0], 3 * sizeof(gb.b[0]), FROM

  #pragma omp target exit data map(from:gb.b[:3]) depend(in: gb.b[:3], la, lb, gc, arg)
  {++arg;}
}





#endif
// CHECK-CK-LABEL: define dso_local void @_Z3fooi(
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2-SAME: i32 noundef signext [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
// CK1-32-_2-_3-SIMD-ONLY0-SAME: i32 noundef [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-CK-NEXT:  [[ENTRY:.*:]]
// CHECK-CK-NEXT:    [[ARG_ADDR:%.*]] = alloca i32, align 4
// CHECK-CK-NEXT:    [[LA:%.*]] = alloca i32, align 4
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2-NEXT:    [[SAVED_STACK:%.*]] = alloca ptr, align 8
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i64, align 8
// CK1-32-_2-_3-SIMD-ONLY0-NEXT:    [[SAVED_STACK:%.*]] = alloca ptr, align 4
// CK1-32-_2-_3-SIMD-ONLY0-NEXT:    [[__VLA_EXPR0:%.*]] = alloca i32, align 4
// CHECK-CK-NEXT:    [[DOTCAPTURE_EXPR_:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 8
// CK1-32-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 4
// CK1-NEXT:    [[AGG_CAPTURED:%.*]] = alloca [[STRUCT_ANON:%.*]], align 4
// CK1-64-NEXT:    [[DOTDEP_ARR_ADDR:%.*]] = alloca [1 x [[STRUCT_KMP_DEPEND_INFO:%.*]]], align 8
// CK1-64-NEXT:    [[DEP_COUNTER_ADDR:%.*]] = alloca i64, align 8
// CK1-32-NEXT:    [[DOTDEP_ARR_ADDR:%.*]] = alloca [1 x [[STRUCT_KMP_DEPEND_INFO:%.*]]], align 4
// CK1-32-NEXT:    [[DEP_COUNTER_ADDR:%.*]] = alloca i32, align 4
// CHECK-CK-NEXT:    [[DOTCAPTURE_EXPR_2:%.*]] = alloca i8, align 1
// CK1-64-NEXT:    [[DOTOFFLOAD_BASEPTRS3:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_PTRS4:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_MAPPERS5:%.*]] = alloca [1 x ptr], align 8
// CK1-32-NEXT:    [[DOTOFFLOAD_BASEPTRS3:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_PTRS4:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_MAPPERS5:%.*]] = alloca [1 x ptr], align 4
// CK1-NEXT:    [[AGG_CAPTURED6:%.*]] = alloca [[STRUCT_ANON_0:%.*]], align 1
// CK1-64-NEXT:    [[DOTDEP_ARR_ADDR9:%.*]] = alloca [3 x [[STRUCT_KMP_DEPEND_INFO]]], align 8
// CK1-64-NEXT:    [[DEP_COUNTER_ADDR10:%.*]] = alloca i64, align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_BASEPTRS13:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_PTRS14:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_MAPPERS15:%.*]] = alloca [1 x ptr], align 8
// CK1-32-NEXT:    [[DOTDEP_ARR_ADDR9:%.*]] = alloca [3 x [[STRUCT_KMP_DEPEND_INFO]]], align 4
// CK1-32-NEXT:    [[DEP_COUNTER_ADDR10:%.*]] = alloca i32, align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_BASEPTRS13:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_PTRS14:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_MAPPERS15:%.*]] = alloca [1 x ptr], align 4
// CK1-NEXT:    [[DOTOFFLOAD_SIZES:%.*]] = alloca [1 x i64], align 8
// CK1-NEXT:    [[AGG_CAPTURED16:%.*]] = alloca [[STRUCT_ANON_3:%.*]], align 1
// CK1-64-NEXT:    [[DOTDEP_ARR_ADDR17:%.*]] = alloca [4 x [[STRUCT_KMP_DEPEND_INFO]]], align 8
// CK1-64-NEXT:    [[DEP_COUNTER_ADDR18:%.*]] = alloca i64, align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_BASEPTRS21:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_PTRS22:%.*]] = alloca [1 x ptr], align 8
// CK1-64-NEXT:    [[DOTOFFLOAD_MAPPERS23:%.*]] = alloca [1 x ptr], align 8
// CK1-32-NEXT:    [[DOTDEP_ARR_ADDR17:%.*]] = alloca [4 x [[STRUCT_KMP_DEPEND_INFO]]], align 4
// CK1-32-NEXT:    [[DEP_COUNTER_ADDR18:%.*]] = alloca i32, align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_BASEPTRS21:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_PTRS22:%.*]] = alloca [1 x ptr], align 4
// CK1-32-NEXT:    [[DOTOFFLOAD_MAPPERS23:%.*]] = alloca [1 x ptr], align 4
// CK1-NEXT:    [[AGG_CAPTURED24:%.*]] = alloca [[STRUCT_ANON_6:%.*]], align 1
// CK1-64-NEXT:    [[DOTDEP_ARR_ADDR25:%.*]] = alloca [5 x [[STRUCT_KMP_DEPEND_INFO]]], align 8
// CK1-64-NEXT:    [[DEP_COUNTER_ADDR28:%.*]] = alloca i64, align 8
// CK1-32-NEXT:    [[DOTDEP_ARR_ADDR25:%.*]] = alloca [5 x [[STRUCT_KMP_DEPEND_INFO]]], align 4
// CK1-32-NEXT:    [[DEP_COUNTER_ADDR28:%.*]] = alloca i32, align 4
// CK1-NEXT:    [[TMP0:%.*]] = call i32 @__kmpc_global_thread_num(ptr @[[GLOB1:[0-9]+]])
// CHECK-CK-NEXT:    store i32 [[ARG]], ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP1]] to i64
// CK1-64-NEXT:    [[TMP3:%.*]] = call ptr @llvm.stacksave.p0()
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[SAVED_STACK]], align 8
// CK1-64-NEXT:    [[VLA:%.*]] = alloca float, i64 [[TMP2]], align 4
// CK1-64-NEXT:    store i64 [[TMP2]], ptr [[__VLA_EXPR0]], align 8
// SIMD-ONLY0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
// CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2-NEXT:    [[TMP2:%.*]] = call ptr @llvm.stacksave.p0()
// CK1-32-NEXT:    store ptr [[TMP2]], ptr [[SAVED_STACK]], align 4
// CK1-32-NEXT:    [[VLA:%.*]] = alloca float, i32 [[TMP1]], align 4
// CK1-32-NEXT:    store i32 [[TMP1]], ptr [[__VLA_EXPR0]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    store ptr [[TMP2]], ptr [[SAVED_STACK]], align 8
// SIMD-ONLY0-_5-_4-NEXT:    [[VLA:%.*]] = alloca float, i64 [[TMP1]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    store i64 [[TMP1]], ptr [[__VLA_EXPR0]], align 8
// SIMD-ONLY0-_3-_2-NEXT:    [[TMP1:%.*]] = call ptr @llvm.stacksave.p0()
// SIMD-ONLY0-_3-_2-NEXT:    store ptr [[TMP1]], ptr [[SAVED_STACK]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[VLA:%.*]] = alloca float, i32 [[TMP0]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[TMP0]], ptr [[__VLA_EXPR0]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[TMP2]], ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-32-_2-_3-SIMD-ONLY0-_5-_4-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-32-_2-_3-SIMD-ONLY0-_5-_4-_2-NEXT:    store i32 [[TMP3]], ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-32-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS]], i32 0, i32 0
// CK1-32-NEXT:    store ptr @gc, ptr [[TMP4]], align 4
// CK1-32-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS]], i32 0, i32 0
// CK1-32-NEXT:    store ptr @gc, ptr [[TMP5]], align 4
// CK1-32-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i32 0, i32 0
// CK1-32-NEXT:    store ptr null, ptr [[TMP6]], align 4
// CK1-32-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT_ANON]], ptr [[AGG_CAPTURED]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP8:%.*]] = load i32, ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-32-NEXT:    store i32 [[TMP8]], ptr [[TMP7]], align 4
// CK1-32-NEXT:    [[TMP9:%.*]] = load i32, ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-32-NEXT:    [[TMP10:%.*]] = sext i32 [[TMP9]] to i64
// CK1-32-NEXT:    [[TMP11:%.*]] = call ptr @__kmpc_omp_target_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i32 36, i32 4, ptr @.omp_task_entry., i64 [[TMP10]])
// CK1-32-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], ptr [[TMP11]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP12]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[TMP13]], align 4
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP14]], ptr align 4 [[AGG_CAPTURED]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES]], ptr [[TMP11]], i32 0, i32 1
// CK1-32-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T:%.*]], ptr [[TMP15]], i32 0, i32 0
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP16]], ptr align 4 @.offload_sizes, i32 8, i1 false)
// CK1-32-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP15]], i32 0, i32 1
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP17]], ptr align 4 [[DOTOFFLOAD_BASEPTRS]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP15]], i32 0, i32 2
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP18]], ptr align 4 [[DOTOFFLOAD_PTRS]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [1 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP20:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i32
// CK1-32-NEXT:    [[TMP21:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP19]], i32 0
// CK1-32-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP21]], i32 0, i32 0
// CK1-32-NEXT:    store i32 [[TMP20]], ptr [[TMP22]], align 4
// CK1-32-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP21]], i32 0, i32 1
// CK1-32-NEXT:    store i32 4, ptr [[TMP23]], align 4
// CK1-32-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP21]], i32 0, i32 2
// CK1-32-NEXT:    store i8 1, ptr [[TMP24]], align 4
// CK1-32-NEXT:    store i32 1, ptr [[DEP_COUNTER_ADDR]], align 4
// CK1-32-NEXT:    [[TMP25:%.*]] = call i32 @__kmpc_omp_task_with_deps(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP11]], i32 1, ptr [[TMP19]], i32 0, ptr null)
// CK1-32-NEXT:    [[TMP26:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-32-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP26]], 1
// SIMD-ONLY0-_3-_2-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP3]], 1
// CK1-32-_2-_3-SIMD-ONLY0-NEXT:    store i32 [[INC]], ptr [[ARG_ADDR]], align 4
// CK1-32-NEXT:    [[TMP27:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-32-NEXT:    [[INC1:%.*]] = add nsw i32 [[TMP27]], 1
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    store i32 [[TMP4]], ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-64-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS]], i32 0, i32 0
// CK1-64-NEXT:    store ptr @gc, ptr [[TMP5]], align 8
// CK1-64-NEXT:    [[TMP6:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS]], i32 0, i32 0
// CK1-64-NEXT:    store ptr @gc, ptr [[TMP6]], align 8
// CK1-64-NEXT:    [[TMP7:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i64 0, i64 0
// CK1-64-NEXT:    store ptr null, ptr [[TMP7]], align 8
// CK1-64-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT_ANON]], ptr [[AGG_CAPTURED]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP9:%.*]] = load i32, ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-64-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
// CK1-64-NEXT:    [[TMP10:%.*]] = load i32, ptr [[DOTCAPTURE_EXPR_]], align 4
// CK1-64-NEXT:    [[TMP11:%.*]] = sext i32 [[TMP10]] to i64
// CK1-64-NEXT:    [[TMP12:%.*]] = call ptr @__kmpc_omp_target_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i64 64, i64 4, ptr @.omp_task_entry., i64 [[TMP11]])
// CK1-64-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], ptr [[TMP12]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP13]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP14]], align 8
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[TMP15]], ptr align 4 [[AGG_CAPTURED]], i64 4, i1 false)
// CK1-64-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES]], ptr [[TMP12]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T:%.*]], ptr [[TMP16]], i32 0, i32 0
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP17]], ptr align 8 [[DOTOFFLOAD_BASEPTRS]], i64 8, i1 false)
// CK1-64-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP16]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP18]], ptr align 8 [[DOTOFFLOAD_PTRS]], i64 8, i1 false)
// CK1-64-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP16]], i32 0, i32 2
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP19]], ptr align 8 @.offload_sizes, i64 8, i1 false)
// CK1-64-NEXT:    [[TMP20:%.*]] = getelementptr inbounds [1 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR]], i64 0, i64 0
// CK1-64-NEXT:    [[TMP21:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i64
// CK1-64-NEXT:    [[TMP22:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP20]], i64 0
// CK1-64-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP22]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP21]], ptr [[TMP23]], align 8
// CK1-64-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP22]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP24]], align 8
// CK1-64-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP22]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP25]], align 8
// CK1-64-NEXT:    store i64 1, ptr [[DEP_COUNTER_ADDR]], align 8
// CK1-64-NEXT:    [[TMP26:%.*]] = call i32 @__kmpc_omp_task_with_deps(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP12]], i32 1, ptr [[TMP20]], i32 0, ptr null)
// CK1-64-NEXT:    [[TMP27:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP27]], 1
// SIMD-ONLY0-_5-_4-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP4]], 1
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2-NEXT:    store i32 [[INC]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[INC1:%.*]] = add nsw i32 [[TMP4]], 1
// CK1-32-_2-_3-SIMD-ONLY0-NEXT:    store i32 [[INC1]], ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[TMP28:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[INC1:%.*]] = add nsw i32 [[TMP28]], 1
// CK1-32-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP28]], 0
// SIMD-ONLY0-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC1:%.*]] = add nsw i32 [[TMP5]], 1
// CK1-64-_3-_2-SIMD-ONLY0-_5-_4-_2-NEXT:    store i32 [[INC1]], ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP29:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP29]], 0
// SIMD-ONLY0-_5-_4-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP6]], 0
// SIMD-ONLY0-_3-_2-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP5]], 0
// CHECK-CK-NEXT:    [[STOREDV:%.*]] = zext i1 [[TOBOOL]] to i8
// CHECK-CK-NEXT:    store i8 [[STOREDV]], ptr [[DOTCAPTURE_EXPR_2]], align 1
// CK1-64-NEXT:    [[TMP30:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR_2]], align 1
// CK1-64-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP30]] to i1
// CK1-32-NEXT:    [[TMP29:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR_2]], align 1
// CK1-32-NEXT:    [[LOADEDV:%.*]] = trunc i8 [[TMP29]] to i1
// CK1-NEXT:    br i1 [[LOADEDV]], label %[[OMP_IF_THEN:.*]], label %[[OMP_IF_ELSE:.*]]
// CK1:       [[OMP_IF_THEN]]:
// CK1-64-NEXT:    [[TMP31:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS3]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[ARG_ADDR]], ptr [[TMP31]], align 8
// CK1-64-NEXT:    [[TMP32:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS4]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[ARG_ADDR]], ptr [[TMP32]], align 8
// CK1-64-NEXT:    [[TMP33:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS5]], i64 0, i64 0
// CK1-64-NEXT:    store ptr null, ptr [[TMP33]], align 8
// CK1-64-NEXT:    [[TMP34:%.*]] = getelementptr inbounds nuw [[STRUCT_ANON_0]], ptr [[AGG_CAPTURED6]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP35:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR_2]], align 1
// CK1-64-NEXT:    [[LOADEDV7:%.*]] = trunc i8 [[TMP35]] to i1
// CK1-32-NEXT:    [[TMP30:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS3]], i32 0, i32 0
// CK1-32-NEXT:    store ptr [[ARG_ADDR]], ptr [[TMP30]], align 4
// CK1-32-NEXT:    [[TMP31:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS4]], i32 0, i32 0
// CK1-32-NEXT:    store ptr [[ARG_ADDR]], ptr [[TMP31]], align 4
// CK1-32-NEXT:    [[TMP32:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS5]], i32 0, i32 0
// CK1-32-NEXT:    store ptr null, ptr [[TMP32]], align 4
// CK1-32-NEXT:    [[TMP33:%.*]] = getelementptr inbounds nuw [[STRUCT_ANON_0]], ptr [[AGG_CAPTURED6]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP34:%.*]] = load i8, ptr [[DOTCAPTURE_EXPR_2]], align 1
// CK1-32-NEXT:    [[LOADEDV7:%.*]] = trunc i8 [[TMP34]] to i1
// CK1-NEXT:    [[STOREDV8:%.*]] = zext i1 [[LOADEDV7]] to i8
// CK1-64-NEXT:    store i8 [[STOREDV8]], ptr [[TMP34]], align 1
// CK1-64-NEXT:    [[TMP36:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i64 64, i64 1, ptr @.omp_task_entry..5)
// CK1-64-NEXT:    [[TMP37:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2:%.*]], ptr [[TMP36]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP38:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP37]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP39:%.*]] = load ptr, ptr [[TMP38]], align 8
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[TMP39]], ptr align 1 [[AGG_CAPTURED6]], i64 1, i1 false)
// CK1-64-NEXT:    [[TMP40:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2]], ptr [[TMP36]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP41:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1:%.*]], ptr [[TMP40]], i32 0, i32 0
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP41]], ptr align 8 [[DOTOFFLOAD_BASEPTRS3]], i64 8, i1 false)
// CK1-64-NEXT:    [[TMP42:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP40]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP42]], ptr align 8 [[DOTOFFLOAD_PTRS4]], i64 8, i1 false)
// CK1-64-NEXT:    [[TMP43:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP40]], i32 0, i32 2
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP43]], ptr align 8 @.offload_sizes.1, i64 8, i1 false)
// CK1-64-NEXT:    [[TMP44:%.*]] = getelementptr inbounds [3 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR9]], i64 0, i64 0
// CK1-64-NEXT:    [[TMP45:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i64
// CK1-64-NEXT:    [[TMP46:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP44]], i64 0
// CK1-64-NEXT:    [[TMP47:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP46]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP45]], ptr [[TMP47]], align 8
// CK1-64-NEXT:    [[TMP48:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP46]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP48]], align 8
// CK1-64-NEXT:    [[TMP49:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP46]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP49]], align 8
// CK1-64-NEXT:    [[TMP50:%.*]] = ptrtoint ptr [[LA]] to i64
// CK1-64-NEXT:    [[TMP51:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP44]], i64 1
// CK1-64-NEXT:    [[TMP52:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP51]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP50]], ptr [[TMP52]], align 8
// CK1-64-NEXT:    [[TMP53:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP51]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP53]], align 8
// CK1-64-NEXT:    [[TMP54:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP51]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP54]], align 8
// CK1-64-NEXT:    [[TMP55:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP44]], i64 2
// CK1-64-NEXT:    [[TMP56:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP55]], i32 0, i32 0
// CK1-64-NEXT:    store i64 ptrtoint (ptr @gc to i64), ptr [[TMP56]], align 8
// CK1-64-NEXT:    [[TMP57:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP55]], i32 0, i32 1
// CK1-64-NEXT:    store i64 800, ptr [[TMP57]], align 8
// CK1-64-NEXT:    [[TMP58:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP55]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP58]], align 8
// CK1-64-NEXT:    store i64 3, ptr [[DEP_COUNTER_ADDR10]], align 8
// CK1-64-NEXT:    call void @__kmpc_omp_taskwait_deps_51(ptr @[[GLOB1]], i32 [[TMP0]], i32 3, ptr [[TMP44]], i32 0, ptr null, i32 0)
// CK1-64-NEXT:    call void @__kmpc_omp_task_begin_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP36]])
// CK1-64-NEXT:    [[TMP59:%.*]] = call i32 @.omp_task_entry..5(i32 [[TMP0]], ptr [[TMP36]]) #[[ATTR2:[0-9]+]]
// CK1-64-NEXT:    call void @__kmpc_omp_task_complete_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP36]])
// CK1-32-NEXT:    store i8 [[STOREDV8]], ptr [[TMP33]], align 1
// CK1-32-NEXT:    [[TMP35:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i32 36, i32 1, ptr @.omp_task_entry..5)
// CK1-32-NEXT:    [[TMP36:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2:%.*]], ptr [[TMP35]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP37:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP36]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP38:%.*]] = load ptr, ptr [[TMP37]], align 4
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[TMP38]], ptr align 1 [[AGG_CAPTURED6]], i32 1, i1 false)
// CK1-32-NEXT:    [[TMP39:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2]], ptr [[TMP35]], i32 0, i32 1
// CK1-32-NEXT:    [[TMP40:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1:%.*]], ptr [[TMP39]], i32 0, i32 0
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP40]], ptr align 4 @.offload_sizes.1, i32 8, i1 false)
// CK1-32-NEXT:    [[TMP41:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP39]], i32 0, i32 1
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP41]], ptr align 4 [[DOTOFFLOAD_BASEPTRS3]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP42:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP39]], i32 0, i32 2
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP42]], ptr align 4 [[DOTOFFLOAD_PTRS4]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP43:%.*]] = getelementptr inbounds [3 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR9]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP44:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i32
// CK1-32-NEXT:    [[TMP45:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP43]], i32 0
// CK1-32-NEXT:    [[TMP46:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP45]], i32 0, i32 0
// CK1-32-NEXT:    store i32 [[TMP44]], ptr [[TMP46]], align 4
// CK1-32-NEXT:    [[TMP47:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP45]], i32 0, i32 1
// CK1-32-NEXT:    store i32 4, ptr [[TMP47]], align 4
// CK1-32-NEXT:    [[TMP48:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP45]], i32 0, i32 2
// CK1-32-NEXT:    store i8 3, ptr [[TMP48]], align 4
// CK1-32-NEXT:    [[TMP49:%.*]] = ptrtoint ptr [[LA]] to i32
// CK1-32-NEXT:    [[TMP50:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP43]], i32 1
// CK1-32-NEXT:    [[TMP51:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP50]], i32 0, i32 0
// CK1-32-NEXT:    store i32 [[TMP49]], ptr [[TMP51]], align 4
// CK1-32-NEXT:    [[TMP52:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP50]], i32 0, i32 1
// CK1-32-NEXT:    store i32 4, ptr [[TMP52]], align 4
// CK1-32-NEXT:    [[TMP53:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP50]], i32 0, i32 2
// CK1-32-NEXT:    store i8 3, ptr [[TMP53]], align 4
// CK1-32-NEXT:    [[TMP54:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP43]], i32 2
// CK1-32-NEXT:    [[TMP55:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP54]], i32 0, i32 0
// CK1-32-NEXT:    store i32 ptrtoint (ptr @gc to i32), ptr [[TMP55]], align 4
// CK1-32-NEXT:    [[TMP56:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP54]], i32 0, i32 1
// CK1-32-NEXT:    store i32 800, ptr [[TMP56]], align 4
// CK1-32-NEXT:    [[TMP57:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP54]], i32 0, i32 2
// CK1-32-NEXT:    store i8 3, ptr [[TMP57]], align 4
// CK1-32-NEXT:    store i32 3, ptr [[DEP_COUNTER_ADDR10]], align 4
// CK1-32-NEXT:    call void @__kmpc_omp_taskwait_deps_51(ptr @[[GLOB1]], i32 [[TMP0]], i32 3, ptr [[TMP43]], i32 0, ptr null, i32 0)
// CK1-32-NEXT:    call void @__kmpc_omp_task_begin_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP35]])
// CK1-32-NEXT:    [[TMP58:%.*]] = call i32 @.omp_task_entry..5(i32 [[TMP0]], ptr [[TMP35]]) #[[ATTR2:[0-9]+]]
// CK1-32-NEXT:    call void @__kmpc_omp_task_complete_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP35]])
// CK1-NEXT:    br label %[[OMP_IF_END:.*]]
// CK1:       [[OMP_IF_ELSE]]:
// CK1-NEXT:    br label %[[OMP_IF_END]]
// CK1:       [[OMP_IF_END]]:
// CK1-32-NEXT:    [[TMP59:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-32-NEXT:    [[INC11:%.*]] = add nsw i32 [[TMP59]], 1
// CK1-32-NEXT:    store i32 [[INC11]], ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[TMP60:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[INC11:%.*]] = add nsw i32 [[TMP60]], 1
// CK1-64-NEXT:    store i32 [[INC11]], ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP61:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[INC12:%.*]] = add nsw i32 [[TMP61]], 1
// CK1-32-NEXT:    [[INC12:%.*]] = add nsw i32 [[TMP60]], 1
// CK1-NEXT:    store i32 [[INC12]], ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP62:%.*]] = mul nuw i64 [[TMP2]], 4
// CK1-32-NEXT:    [[TMP61:%.*]] = mul nuw i32 [[TMP1]], 4
// CK1-32-NEXT:    [[TMP62:%.*]] = sext i32 [[TMP61]] to i64
// CK1-NEXT:    [[TMP63:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS13]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[VLA]], ptr [[TMP63]], align 8
// CK1-32-NEXT:    store ptr [[VLA]], ptr [[TMP63]], align 4
// CK1-NEXT:    [[TMP64:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS14]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[VLA]], ptr [[TMP64]], align 8
// CK1-32-NEXT:    store ptr [[VLA]], ptr [[TMP64]], align 4
// CK1-NEXT:    [[TMP65:%.*]] = getelementptr inbounds [1 x i64], ptr [[DOTOFFLOAD_SIZES]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP62]], ptr [[TMP65]], align 8
// CK1-64-NEXT:    [[TMP66:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS15]], i64 0, i64 0
// CK1-64-NEXT:    store ptr null, ptr [[TMP66]], align 8
// CK1-64-NEXT:    [[TMP67:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i64 64, i64 1, ptr @.omp_task_entry..9)
// CK1-32-NEXT:    store i64 [[TMP62]], ptr [[TMP65]], align 4
// CK1-32-NEXT:    [[TMP66:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS15]], i32 0, i32 0
// CK1-32-NEXT:    store ptr null, ptr [[TMP66]], align 4
// CK1-32-NEXT:    [[TMP67:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i32 36, i32 1, ptr @.omp_task_entry..9)
// CK1-NEXT:    [[TMP68:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_5:%.*]], ptr [[TMP67]], i32 0, i32 0
// CK1-NEXT:    [[TMP69:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_5]], ptr [[TMP67]], i32 0, i32 1
// CK1-NEXT:    [[TMP70:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4:%.*]], ptr [[TMP69]], i32 0, i32 0
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP70]], ptr align 8 [[DOTOFFLOAD_BASEPTRS13]], i64 8, i1 false)
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP70]], ptr align 4 [[DOTOFFLOAD_SIZES]], i32 8, i1 false)
// CK1-NEXT:    [[TMP71:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4]], ptr [[TMP69]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP71]], ptr align 8 [[DOTOFFLOAD_PTRS14]], i64 8, i1 false)
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP71]], ptr align 4 [[DOTOFFLOAD_BASEPTRS13]], i32 4, i1 false)
// CK1-NEXT:    [[TMP72:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4]], ptr [[TMP69]], i32 0, i32 2
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP72]], ptr align 8 [[DOTOFFLOAD_SIZES]], i64 8, i1 false)
// CK1-64-NEXT:    [[TMP73:%.*]] = getelementptr inbounds [4 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR17]], i64 0, i64 0
// CK1-64-NEXT:    [[TMP74:%.*]] = mul nuw i64 [[TMP2]], 4
// CK1-64-NEXT:    [[TMP75:%.*]] = ptrtoint ptr [[VLA]] to i64
// CK1-64-NEXT:    [[TMP76:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i64 0
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP72]], ptr align 4 [[DOTOFFLOAD_PTRS14]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP73:%.*]] = getelementptr inbounds [4 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR17]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP74:%.*]] = mul nuw i32 [[TMP1]], 4
// CK1-32-NEXT:    [[TMP75:%.*]] = ptrtoint ptr [[VLA]] to i32
// CK1-32-NEXT:    [[TMP76:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i32 0
// CK1-NEXT:    [[TMP77:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP76]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP75]], ptr [[TMP77]], align 8
// CK1-32-NEXT:    store i32 [[TMP75]], ptr [[TMP77]], align 4
// CK1-NEXT:    [[TMP78:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP76]], i32 0, i32 1
// CK1-64-NEXT:    store i64 [[TMP74]], ptr [[TMP78]], align 8
// CK1-32-NEXT:    store i32 [[TMP74]], ptr [[TMP78]], align 4
// CK1-NEXT:    [[TMP79:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP76]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP79]], align 8
// CK1-64-NEXT:    [[TMP80:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i64
// CK1-64-NEXT:    [[TMP81:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i64 1
// CK1-32-NEXT:    store i8 3, ptr [[TMP79]], align 4
// CK1-32-NEXT:    [[TMP80:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i32
// CK1-32-NEXT:    [[TMP81:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i32 1
// CK1-NEXT:    [[TMP82:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP81]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP80]], ptr [[TMP82]], align 8
// CK1-32-NEXT:    store i32 [[TMP80]], ptr [[TMP82]], align 4
// CK1-NEXT:    [[TMP83:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP81]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP83]], align 8
// CK1-32-NEXT:    store i32 4, ptr [[TMP83]], align 4
// CK1-NEXT:    [[TMP84:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP81]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP84]], align 8
// CK1-64-NEXT:    [[TMP85:%.*]] = ptrtoint ptr [[LA]] to i64
// CK1-64-NEXT:    [[TMP86:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i64 2
// CK1-32-NEXT:    store i8 3, ptr [[TMP84]], align 4
// CK1-32-NEXT:    [[TMP85:%.*]] = ptrtoint ptr [[LA]] to i32
// CK1-32-NEXT:    [[TMP86:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i32 2
// CK1-NEXT:    [[TMP87:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP86]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP85]], ptr [[TMP87]], align 8
// CK1-32-NEXT:    store i32 [[TMP85]], ptr [[TMP87]], align 4
// CK1-NEXT:    [[TMP88:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP86]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP88]], align 8
// CK1-32-NEXT:    store i32 4, ptr [[TMP88]], align 4
// CK1-NEXT:    [[TMP89:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP86]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP89]], align 8
// CK1-64-NEXT:    [[TMP90:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i64 3
// CK1-32-NEXT:    store i8 3, ptr [[TMP89]], align 4
// CK1-32-NEXT:    [[TMP90:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP73]], i32 3
// CK1-NEXT:    [[TMP91:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP90]], i32 0, i32 0
// CK1-64-NEXT:    store i64 ptrtoint (ptr @gc to i64), ptr [[TMP91]], align 8
// CK1-32-NEXT:    store i32 ptrtoint (ptr @gc to i32), ptr [[TMP91]], align 4
// CK1-NEXT:    [[TMP92:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP90]], i32 0, i32 1
// CK1-64-NEXT:    store i64 800, ptr [[TMP92]], align 8
// CK1-32-NEXT:    store i32 800, ptr [[TMP92]], align 4
// CK1-NEXT:    [[TMP93:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP90]], i32 0, i32 2
// CK1-64-NEXT:    store i8 3, ptr [[TMP93]], align 8
// CK1-64-NEXT:    store i64 4, ptr [[DEP_COUNTER_ADDR18]], align 8
// CK1-32-NEXT:    store i8 3, ptr [[TMP93]], align 4
// CK1-32-NEXT:    store i32 4, ptr [[DEP_COUNTER_ADDR18]], align 4
// CK1-NEXT:    call void @__kmpc_omp_taskwait_deps_51(ptr @[[GLOB1]], i32 [[TMP0]], i32 4, ptr [[TMP73]], i32 0, ptr null, i32 0)
// CK1-NEXT:    call void @__kmpc_omp_task_begin_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP67]])
// CK1-NEXT:    [[TMP94:%.*]] = call i32 @.omp_task_entry..9(i32 [[TMP0]], ptr [[TMP67]]) #[[ATTR2]]
// CK1-NEXT:    call void @__kmpc_omp_task_complete_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP67]])
// CK1-NEXT:    [[TMP95:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[INC19:%.*]] = add nsw i32 [[TMP95]], 1
// CK1-NEXT:    store i32 [[INC19]], ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[TMP96:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[INC20:%.*]] = add nsw i32 [[TMP96]], 1
// CK1-NEXT:    store i32 [[INC20]], ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP97:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST:%.*]], ptr @gb, i32 0, i32 1), align 8
// CK1-64-NEXT:    [[TMP98:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 8
// CK1-64-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw double, ptr [[TMP98]], i64 0
// CK1-32-NEXT:    [[TMP97:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST:%.*]], ptr @gb, i32 0, i32 1), align 4
// CK1-32-NEXT:    [[TMP98:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 4
// CK1-32-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw double, ptr [[TMP98]], i32 0
// CK1-NEXT:    [[TMP99:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS21]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[TMP97]], ptr [[TMP99]], align 8
// CK1-32-NEXT:    store ptr [[TMP97]], ptr [[TMP99]], align 4
// CK1-NEXT:    [[TMP100:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS22]], i32 0, i32 0
// CK1-64-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP100]], align 8
// CK1-64-NEXT:    [[TMP101:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS23]], i64 0, i64 0
// CK1-64-NEXT:    store ptr null, ptr [[TMP101]], align 8
// CK1-64-NEXT:    [[TMP102:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i64 64, i64 1, ptr @.omp_task_entry..14)
// CK1-32-NEXT:    store ptr [[ARRAYIDX]], ptr [[TMP100]], align 4
// CK1-32-NEXT:    [[TMP101:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS23]], i32 0, i32 0
// CK1-32-NEXT:    store ptr null, ptr [[TMP101]], align 4
// CK1-32-NEXT:    [[TMP102:%.*]] = call ptr @__kmpc_omp_task_alloc(ptr @[[GLOB1]], i32 [[TMP0]], i32 1, i32 36, i32 1, ptr @.omp_task_entry..14)
// CK1-NEXT:    [[TMP103:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_8:%.*]], ptr [[TMP102]], i32 0, i32 0
// CK1-NEXT:    [[TMP104:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_8]], ptr [[TMP102]], i32 0, i32 1
// CK1-NEXT:    [[TMP105:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7:%.*]], ptr [[TMP104]], i32 0, i32 0
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP105]], ptr align 8 [[DOTOFFLOAD_BASEPTRS21]], i64 8, i1 false)
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP105]], ptr align 4 @.offload_sizes.10, i32 8, i1 false)
// CK1-NEXT:    [[TMP106:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7]], ptr [[TMP104]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP106]], ptr align 8 [[DOTOFFLOAD_PTRS22]], i64 8, i1 false)
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP106]], ptr align 4 [[DOTOFFLOAD_BASEPTRS21]], i32 4, i1 false)
// CK1-NEXT:    [[TMP107:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7]], ptr [[TMP104]], i32 0, i32 2
// CK1-64-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP107]], ptr align 8 @.offload_sizes.10, i64 8, i1 false)
// CK1-64-NEXT:    [[TMP108:%.*]] = getelementptr inbounds [5 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR25]], i64 0, i64 0
// CK1-64-NEXT:    [[TMP109:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 8
// CK1-64-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds nuw double, ptr [[TMP109]], i64 0
// CK1-64-NEXT:    [[TMP110:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 8
// CK1-64-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds nuw double, ptr [[TMP110]], i64 2
// CK1-32-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[TMP107]], ptr align 4 [[DOTOFFLOAD_PTRS22]], i32 4, i1 false)
// CK1-32-NEXT:    [[TMP108:%.*]] = getelementptr inbounds [5 x [[STRUCT_KMP_DEPEND_INFO]]], ptr [[DOTDEP_ARR_ADDR25]], i32 0, i32 0
// CK1-32-NEXT:    [[TMP109:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 4
// CK1-32-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds nuw double, ptr [[TMP109]], i32 0
// CK1-32-NEXT:    [[TMP110:%.*]] = load ptr, ptr getelementptr inbounds nuw ([[STRUCT_ST]], ptr @gb, i32 0, i32 1), align 4
// CK1-32-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds nuw double, ptr [[TMP110]], i32 2
// CK1-NEXT:    [[TMP111:%.*]] = getelementptr double, ptr [[ARRAYIDX27]], i32 1
// CK1-64-NEXT:    [[TMP112:%.*]] = ptrtoint ptr [[ARRAYIDX26]] to i64
// CK1-64-NEXT:    [[TMP113:%.*]] = ptrtoint ptr [[TMP111]] to i64
// CK1-64-NEXT:    [[TMP114:%.*]] = sub nuw i64 [[TMP113]], [[TMP112]]
// CK1-64-NEXT:    [[TMP115:%.*]] = ptrtoint ptr [[ARRAYIDX26]] to i64
// CK1-64-NEXT:    [[TMP116:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i64 0
// CK1-32-NEXT:    [[TMP112:%.*]] = ptrtoint ptr [[ARRAYIDX26]] to i32
// CK1-32-NEXT:    [[TMP113:%.*]] = ptrtoint ptr [[TMP111]] to i32
// CK1-32-NEXT:    [[TMP114:%.*]] = sub nuw i32 [[TMP113]], [[TMP112]]
// CK1-32-NEXT:    [[TMP115:%.*]] = ptrtoint ptr [[ARRAYIDX26]] to i32
// CK1-32-NEXT:    [[TMP116:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i32 0
// CK1-NEXT:    [[TMP117:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP116]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP115]], ptr [[TMP117]], align 8
// CK1-32-NEXT:    store i32 [[TMP115]], ptr [[TMP117]], align 4
// CK1-NEXT:    [[TMP118:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP116]], i32 0, i32 1
// CK1-64-NEXT:    store i64 [[TMP114]], ptr [[TMP118]], align 8
// CK1-32-NEXT:    store i32 [[TMP114]], ptr [[TMP118]], align 4
// CK1-NEXT:    [[TMP119:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP116]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP119]], align 8
// CK1-64-NEXT:    [[TMP120:%.*]] = ptrtoint ptr [[LA]] to i64
// CK1-64-NEXT:    [[TMP121:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i64 1
// CK1-32-NEXT:    store i8 1, ptr [[TMP119]], align 4
// CK1-32-NEXT:    [[TMP120:%.*]] = ptrtoint ptr [[LA]] to i32
// CK1-32-NEXT:    [[TMP121:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i32 1
// CK1-NEXT:    [[TMP122:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP121]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP120]], ptr [[TMP122]], align 8
// CK1-32-NEXT:    store i32 [[TMP120]], ptr [[TMP122]], align 4
// CK1-NEXT:    [[TMP123:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP121]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP123]], align 8
// CK1-32-NEXT:    store i32 4, ptr [[TMP123]], align 4
// CK1-NEXT:    [[TMP124:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP121]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP124]], align 8
// CK1-64-NEXT:    [[TMP125:%.*]] = mul nuw i64 [[TMP2]], 4
// CK1-64-NEXT:    [[TMP126:%.*]] = ptrtoint ptr [[VLA]] to i64
// CK1-64-NEXT:    [[TMP127:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i64 2
// CK1-32-NEXT:    store i8 1, ptr [[TMP124]], align 4
// CK1-32-NEXT:    [[TMP125:%.*]] = mul nuw i32 [[TMP1]], 4
// CK1-32-NEXT:    [[TMP126:%.*]] = ptrtoint ptr [[VLA]] to i32
// CK1-32-NEXT:    [[TMP127:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i32 2
// CK1-NEXT:    [[TMP128:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP127]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP126]], ptr [[TMP128]], align 8
// CK1-32-NEXT:    store i32 [[TMP126]], ptr [[TMP128]], align 4
// CK1-NEXT:    [[TMP129:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP127]], i32 0, i32 1
// CK1-64-NEXT:    store i64 [[TMP125]], ptr [[TMP129]], align 8
// CK1-32-NEXT:    store i32 [[TMP125]], ptr [[TMP129]], align 4
// CK1-NEXT:    [[TMP130:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP127]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP130]], align 8
// CK1-64-NEXT:    [[TMP131:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i64 3
// CK1-32-NEXT:    store i8 1, ptr [[TMP130]], align 4
// CK1-32-NEXT:    [[TMP131:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i32 3
// CK1-NEXT:    [[TMP132:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP131]], i32 0, i32 0
// CK1-64-NEXT:    store i64 ptrtoint (ptr @gc to i64), ptr [[TMP132]], align 8
// CK1-32-NEXT:    store i32 ptrtoint (ptr @gc to i32), ptr [[TMP132]], align 4
// CK1-NEXT:    [[TMP133:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP131]], i32 0, i32 1
// CK1-64-NEXT:    store i64 800, ptr [[TMP133]], align 8
// CK1-32-NEXT:    store i32 800, ptr [[TMP133]], align 4
// CK1-NEXT:    [[TMP134:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP131]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP134]], align 8
// CK1-64-NEXT:    [[TMP135:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i64
// CK1-64-NEXT:    [[TMP136:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i64 4
// CK1-32-NEXT:    store i8 1, ptr [[TMP134]], align 4
// CK1-32-NEXT:    [[TMP135:%.*]] = ptrtoint ptr [[ARG_ADDR]] to i32
// CK1-32-NEXT:    [[TMP136:%.*]] = getelementptr [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP108]], i32 4
// CK1-NEXT:    [[TMP137:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP136]], i32 0, i32 0
// CK1-64-NEXT:    store i64 [[TMP135]], ptr [[TMP137]], align 8
// CK1-32-NEXT:    store i32 [[TMP135]], ptr [[TMP137]], align 4
// CK1-NEXT:    [[TMP138:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP136]], i32 0, i32 1
// CK1-64-NEXT:    store i64 4, ptr [[TMP138]], align 8
// CK1-32-NEXT:    store i32 4, ptr [[TMP138]], align 4
// CK1-NEXT:    [[TMP139:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_DEPEND_INFO]], ptr [[TMP136]], i32 0, i32 2
// CK1-64-NEXT:    store i8 1, ptr [[TMP139]], align 8
// CK1-64-NEXT:    store i64 5, ptr [[DEP_COUNTER_ADDR28]], align 8
// CK1-32-NEXT:    store i8 1, ptr [[TMP139]], align 4
// CK1-32-NEXT:    store i32 5, ptr [[DEP_COUNTER_ADDR28]], align 4
// CK1-NEXT:    call void @__kmpc_omp_taskwait_deps_51(ptr @[[GLOB1]], i32 [[TMP0]], i32 5, ptr [[TMP108]], i32 0, ptr null, i32 0)
// CK1-NEXT:    call void @__kmpc_omp_task_begin_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP102]])
// CK1-NEXT:    [[TMP140:%.*]] = call i32 @.omp_task_entry..14(i32 [[TMP0]], ptr [[TMP102]]) #[[ATTR2]]
// CK1-NEXT:    call void @__kmpc_omp_task_complete_if0(ptr @[[GLOB1]], i32 [[TMP0]], ptr [[TMP102]])
// CK1-NEXT:    [[TMP141:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// CK1-NEXT:    [[INC29:%.*]] = add nsw i32 [[TMP141]], 1
// CK1-NEXT:    store i32 [[INC29]], ptr [[ARG_ADDR]], align 4
// CK1-64-NEXT:    [[TMP142:%.*]] = load ptr, ptr [[SAVED_STACK]], align 8
// CK1-32-NEXT:    [[TMP142:%.*]] = load ptr, ptr [[SAVED_STACK]], align 4
// CK1-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP142]])
// SIMD-ONLY0-_3-_2-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[INC3:%.*]] = add nsw i32 [[TMP6]], 1
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[INC3]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC3:%.*]] = add nsw i32 [[TMP7]], 1
// SIMD-ONLY0-_5-_4-NEXT:    store i32 [[INC3]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[INC4:%.*]] = add nsw i32 [[TMP7]], 1
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[INC4]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC4:%.*]] = add nsw i32 [[TMP8]], 1
// SIMD-ONLY0-_5-_4-NEXT:    store i32 [[INC4]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[INC5:%.*]] = add nsw i32 [[TMP8]], 1
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[INC5]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC5:%.*]] = add nsw i32 [[TMP9]], 1
// SIMD-ONLY0-_5-_4-NEXT:    store i32 [[INC5]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    [[INC6:%.*]] = add nsw i32 [[TMP9]], 1
// SIMD-ONLY0-_3-_2-NEXT:    store i32 [[INC6]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC6:%.*]] = add nsw i32 [[TMP10]], 1
// SIMD-ONLY0-_5-_4-NEXT:    store i32 [[INC6]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[INC7:%.*]] = add nsw i32 [[TMP11]], 1
// SIMD-ONLY0-_3-_2-NEXT:    [[INC7:%.*]] = add nsw i32 [[TMP10]], 1
// SIMD-ONLY0-NEXT:    store i32 [[INC7]], ptr [[ARG_ADDR]], align 4
// SIMD-ONLY0-_5-_4-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[SAVED_STACK]], align 8
// SIMD-ONLY0-_5-_4-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP12]])
// SIMD-ONLY0-_3-_2-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[SAVED_STACK]], align 4
// SIMD-ONLY0-_3-_2-NEXT:    call void @llvm.stackrestore.p0(ptr [[TMP11]])
// CHECK-CK-NEXT:    ret void
//
//
// CK1-LABEL: define internal void @.omp_task_privates_map.(
// CK1-SAME: ptr noalias noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]], ptr noalias noundef [[TMP2:%.*]], ptr noalias noundef [[TMP3:%.*]]) #[[ATTR3:[0-9]+]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-64-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 8
// CK1-32-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 4
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T:%.*]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP4]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// CK1-32-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 4
// CK1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T]], ptr [[TMP4]], i32 0, i32 2
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 8
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 4
// CK1-NEXT:    ret void
//
//
// CK1-64-LABEL: define internal noundef signext i32 @.omp_task_entry.(
// CK1-64-SAME: i32 noundef signext [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4:[0-9]+]] {
// CK1-32-LABEL: define internal noundef i32 @.omp_task_entry.(
// CK1-32-SAME: i32 noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4:[0-9]+]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-NEXT:    [[DOTGLOBAL_TID__ADDR_I:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 4
// CK1-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-NEXT:    store i32 [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES:%.*]], ptr [[TMP3]], i32 0, i32 0
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP4]], i32 0, i32 2
// CK1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES]], ptr [[TMP3]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META3:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META6:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META8:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META10:![0-9]+]])
// CK1-64-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META12:![0-9]+]]
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    store ptr @.omp_task_privates_map., ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META12]]
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META4:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META7:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META9:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META11:![0-9]+]])
// CK1-32-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META13:![0-9]+]]
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    store ptr @.omp_task_privates_map., ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META13]]
// CK1-NEXT:    call void [[TMP10]](ptr [[TMP11]], ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]]) #[[ATTR2]]
// CK1-64-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 8, !noalias [[META12]]
// CK1-64-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 8, !noalias [[META12]]
// CK1-32-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 4, !noalias [[META13]]
// CK1-32-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 4, !noalias [[META13]]
// CK1-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP9]], align 4
// CK1-NEXT:    [[TMP16:%.*]] = sext i32 [[TMP15]] to i64
// CK1-NEXT:    call void @__tgt_target_data_end_nowait_mapper(ptr @[[GLOB1]], i64 [[TMP16]], i32 1, ptr [[TMP12]], ptr [[TMP13]], ptr [[TMP14]], ptr @.offload_maptypes, ptr null, ptr null, i32 0, ptr null, i32 0, ptr null)
// CK1-NEXT:    ret i32 0
//
//
// CK1-LABEL: define internal void @.omp_task_privates_map..4(
// CK1-SAME: ptr noalias noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]], ptr noalias noundef [[TMP2:%.*]], ptr noalias noundef [[TMP3:%.*]]) #[[ATTR3]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-64-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 8
// CK1-32-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 4
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1:%.*]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP4]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// CK1-32-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 4
// CK1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_1]], ptr [[TMP4]], i32 0, i32 2
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 8
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 4
// CK1-NEXT:    ret void
//
//
// CK1-64-LABEL: define internal noundef signext i32 @.omp_task_entry..5(
// CK1-64-SAME: i32 noundef signext [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-32-LABEL: define internal noundef i32 @.omp_task_entry..5(
// CK1-32-SAME: i32 noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-NEXT:    [[DOTGLOBAL_TID__ADDR_I:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 4
// CK1-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-NEXT:    store i32 [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2:%.*]], ptr [[TMP3]], i32 0, i32 0
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP4]], i32 0, i32 2
// CK1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_2]], ptr [[TMP3]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META13:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META16:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META18:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META20:![0-9]+]])
// CK1-64-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META22:![0-9]+]]
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    store ptr @.omp_task_privates_map..4, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META22]]
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META14:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META17:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META19:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META21:![0-9]+]])
// CK1-32-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META23:![0-9]+]]
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    store ptr @.omp_task_privates_map..4, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META23]]
// CK1-NEXT:    call void [[TMP10]](ptr [[TMP11]], ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]]) #[[ATTR2]]
// CK1-64-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 8, !noalias [[META22]]
// CK1-64-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 8, !noalias [[META22]]
// CK1-32-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 4, !noalias [[META23]]
// CK1-32-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 4, !noalias [[META23]]
// CK1-NEXT:    call void @__tgt_target_data_end_mapper(ptr @[[GLOB1]], i64 4, i32 1, ptr [[TMP12]], ptr [[TMP13]], ptr [[TMP14]], ptr @.offload_maptypes.2, ptr null, ptr null)
// CK1-NEXT:    ret i32 0
//
//
// CK1-LABEL: define internal void @.omp_task_privates_map..8(
// CK1-SAME: ptr noalias noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]], ptr noalias noundef [[TMP2:%.*]], ptr noalias noundef [[TMP3:%.*]]) #[[ATTR3]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-64-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 8
// CK1-32-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 4
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4:%.*]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4]], ptr [[TMP4]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// CK1-32-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 4
// CK1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_4]], ptr [[TMP4]], i32 0, i32 2
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 8
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 4
// CK1-NEXT:    ret void
//
//
// CK1-64-LABEL: define internal noundef signext i32 @.omp_task_entry..9(
// CK1-64-SAME: i32 noundef signext [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-32-LABEL: define internal noundef i32 @.omp_task_entry..9(
// CK1-32-SAME: i32 noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-NEXT:    [[DOTGLOBAL_TID__ADDR_I:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 4
// CK1-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-NEXT:    store i32 [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_5:%.*]], ptr [[TMP3]], i32 0, i32 0
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP4]], i32 0, i32 2
// CK1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_5]], ptr [[TMP3]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META23:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META26:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META28:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META30:![0-9]+]])
// CK1-64-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META32:![0-9]+]]
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    store ptr @.omp_task_privates_map..8, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META32]]
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META24:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META27:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META29:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META31:![0-9]+]])
// CK1-32-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META33:![0-9]+]]
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    store ptr @.omp_task_privates_map..8, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META33]]
// CK1-NEXT:    call void [[TMP10]](ptr [[TMP11]], ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]]) #[[ATTR2]]
// CK1-64-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 8, !noalias [[META32]]
// CK1-64-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 8, !noalias [[META32]]
// CK1-32-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 4, !noalias [[META33]]
// CK1-32-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 4, !noalias [[META33]]
// CK1-NEXT:    call void @__tgt_target_data_end_mapper(ptr @[[GLOB1]], i64 -1, i32 1, ptr [[TMP12]], ptr [[TMP13]], ptr [[TMP14]], ptr @.offload_maptypes.6, ptr null, ptr null)
// CK1-NEXT:    ret i32 0
//
//
// CK1-LABEL: define internal void @.omp_task_privates_map..13(
// CK1-SAME: ptr noalias noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]], ptr noalias noundef [[TMP2:%.*]], ptr noalias noundef [[TMP3:%.*]]) #[[ATTR3]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-64-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 8
// CK1-32-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR2:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTADDR3:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP2]], ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[DOTADDR]], align 4
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7:%.*]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP6:%.*]] = load ptr, ptr [[DOTADDR3]], align 4
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7]], ptr [[TMP4]], i32 0, i32 1
// CK1-64-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR2]], align 8
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// CK1-32-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 4
// CK1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT__KMP_PRIVATES_T_7]], ptr [[TMP4]], i32 0, i32 2
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR3]], align 8
// CK1-64-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 8
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTADDR2]], align 4
// CK1-32-NEXT:    store ptr [[TMP9]], ptr [[TMP10]], align 4
// CK1-NEXT:    ret void
//
//
// CK1-64-LABEL: define internal noundef signext i32 @.omp_task_entry..14(
// CK1-64-SAME: i32 noundef signext [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-32-LABEL: define internal noundef i32 @.omp_task_entry..14(
// CK1-32-SAME: i32 noundef [[TMP0:%.*]], ptr noalias noundef [[TMP1:%.*]]) #[[ATTR4]] {
// CK1-NEXT:  [[ENTRY:.*:]]
// CK1-NEXT:    [[DOTGLOBAL_TID__ADDR_I:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 8
// CK1-64-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTPART_ID__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTPRIVATES__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTCOPY_FN__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTTASK_T__ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[__CONTEXT_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR1_I:%.*]] = alloca ptr, align 4
// CK1-32-NEXT:    [[DOTFIRSTPRIV_PTR_ADDR2_I:%.*]] = alloca ptr, align 4
// CK1-NEXT:    [[DOTADDR:%.*]] = alloca i32, align 4
// CK1-64-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 8
// CK1-32-NEXT:    [[DOTADDR1:%.*]] = alloca ptr, align 4
// CK1-NEXT:    store i32 [[TMP0]], ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    store ptr [[TMP1]], ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP2:%.*]] = load i32, ptr [[DOTADDR]], align 4
// CK1-64-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 8
// CK1-32-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DOTADDR1]], align 4
// CK1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_8:%.*]], ptr [[TMP3]], i32 0, i32 0
// CK1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T:%.*]], ptr [[TMP4]], i32 0, i32 2
// CK1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T]], ptr [[TMP4]], i32 0, i32 0
// CK1-64-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// CK1-32-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 4
// CK1-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT_KMP_TASK_T_WITH_PRIVATES_8]], ptr [[TMP3]], i32 0, i32 1
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META33:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META36:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META38:![0-9]+]])
// CK1-64-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META40:![0-9]+]])
// CK1-64-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META42:![0-9]+]]
// CK1-64-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    store ptr @.omp_task_privates_map..13, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 8, !noalias [[META42]]
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META34:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META37:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META39:![0-9]+]])
// CK1-32-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META41:![0-9]+]])
// CK1-32-NEXT:    store i32 [[TMP2]], ptr [[DOTGLOBAL_TID__ADDR_I]], align 4, !noalias [[META43:![0-9]+]]
// CK1-32-NEXT:    store ptr [[TMP5]], ptr [[DOTPART_ID__ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    store ptr [[TMP8]], ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    store ptr @.omp_task_privates_map..13, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    store ptr [[TMP3]], ptr [[DOTTASK_T__ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    store ptr [[TMP7]], ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[__CONTEXT_ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[DOTCOPY_FN__ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[DOTPRIVATES__ADDR_I]], align 4, !noalias [[META43]]
// CK1-NEXT:    call void [[TMP10]](ptr [[TMP11]], ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]]) #[[ATTR2]]
// CK1-64-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 8, !noalias [[META42]]
// CK1-64-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 8, !noalias [[META42]]
// CK1-32-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR1_I]], align 4, !noalias [[META43]]
// CK1-32-NEXT:    [[TMP14:%.*]] = load ptr, ptr [[DOTFIRSTPRIV_PTR_ADDR2_I]], align 4, !noalias [[META43]]
// CK1-NEXT:    call void @__tgt_target_data_end_mapper(ptr @[[GLOB1]], i64 -1, i32 1, ptr [[TMP12]], ptr [[TMP13]], ptr [[TMP14]], ptr @.offload_maptypes.11, ptr null, ptr null)
// CK1-NEXT:    ret i32 0
//
//
// CK1-64: [[META3]] = !{[[META4:![0-9]+]]}
// CK1-64: [[META4]] = distinct !{[[META4]], [[META5:![0-9]+]], !".omp_outlined.: %dotpart_id."}
// CK1-64: [[META5]] = distinct !{[[META5]], !".omp_outlined."}
// CK1-64: [[META6]] = !{[[META7:![0-9]+]]}
// CK1-64: [[META7]] = distinct !{[[META7]], [[META5]], !".omp_outlined.: %dotprivates."}
// CK1-64: [[META8]] = !{[[META9:![0-9]+]]}
// CK1-64: [[META9]] = distinct !{[[META9]], [[META5]], !".omp_outlined.: %dotcopy_fn."}
// CK1-64: [[META10]] = !{[[META11:![0-9]+]]}
// CK1-64: [[META11]] = distinct !{[[META11]], [[META5]], !".omp_outlined.: %__context"}
// CK1-64: [[META12]] = !{[[META4]], [[META7]], [[META9]], [[META11]]}
// CK1-64: [[META13]] = !{[[META14:![0-9]+]]}
// CK1-64: [[META14]] = distinct !{[[META14]], [[META15:![0-9]+]], !".omp_outlined..3: %dotpart_id."}
// CK1-64: [[META15]] = distinct !{[[META15]], !".omp_outlined..3"}
// CK1-64: [[META16]] = !{[[META17:![0-9]+]]}
// CK1-64: [[META17]] = distinct !{[[META17]], [[META15]], !".omp_outlined..3: %dotprivates."}
// CK1-64: [[META18]] = !{[[META19:![0-9]+]]}
// CK1-64: [[META19]] = distinct !{[[META19]], [[META15]], !".omp_outlined..3: %dotcopy_fn."}
// CK1-64: [[META20]] = !{[[META21:![0-9]+]]}
// CK1-64: [[META21]] = distinct !{[[META21]], [[META15]], !".omp_outlined..3: %__context"}
// CK1-64: [[META22]] = !{[[META14]], [[META17]], [[META19]], [[META21]]}
// CK1-64: [[META23]] = !{[[META24:![0-9]+]]}
// CK1-64: [[META24]] = distinct !{[[META24]], [[META25:![0-9]+]], !".omp_outlined..7: %dotpart_id."}
// CK1-64: [[META25]] = distinct !{[[META25]], !".omp_outlined..7"}
// CK1-64: [[META26]] = !{[[META27:![0-9]+]]}
// CK1-64: [[META27]] = distinct !{[[META27]], [[META25]], !".omp_outlined..7: %dotprivates."}
// CK1-64: [[META28]] = !{[[META29:![0-9]+]]}
// CK1-64: [[META29]] = distinct !{[[META29]], [[META25]], !".omp_outlined..7: %dotcopy_fn."}
// CK1-64: [[META30]] = !{[[META31:![0-9]+]]}
// CK1-64: [[META31]] = distinct !{[[META31]], [[META25]], !".omp_outlined..7: %__context"}
// CK1-64: [[META32]] = !{[[META24]], [[META27]], [[META29]], [[META31]]}
// CK1-64: [[META33]] = !{[[META34:![0-9]+]]}
// CK1-64: [[META34]] = distinct !{[[META34]], [[META35:![0-9]+]], !".omp_outlined..12: %dotpart_id."}
// CK1-64: [[META35]] = distinct !{[[META35]], !".omp_outlined..12"}
// CK1-64: [[META36]] = !{[[META37:![0-9]+]]}
// CK1-64: [[META37]] = distinct !{[[META37]], [[META35]], !".omp_outlined..12: %dotprivates."}
// CK1-64: [[META38]] = !{[[META39:![0-9]+]]}
// CK1-64: [[META39]] = distinct !{[[META39]], [[META35]], !".omp_outlined..12: %dotcopy_fn."}
// CK1-64: [[META40]] = !{[[META41:![0-9]+]]}
// CK1-64: [[META41]] = distinct !{[[META41]], [[META35]], !".omp_outlined..12: %__context"}
// CK1-64: [[META42]] = !{[[META34]], [[META37]], [[META39]], [[META41]]}
// CK1-32: [[META4]] = !{[[META5:![0-9]+]]}
// CK1-32: [[META5]] = distinct !{[[META5]], [[META6:![0-9]+]], !".omp_outlined.: %dotpart_id."}
// CK1-32: [[META6]] = distinct !{[[META6]], !".omp_outlined."}
// CK1-32: [[META7]] = !{[[META8:![0-9]+]]}
// CK1-32: [[META8]] = distinct !{[[META8]], [[META6]], !".omp_outlined.: %dotprivates."}
// CK1-32: [[META9]] = !{[[META10:![0-9]+]]}
// CK1-32: [[META10]] = distinct !{[[META10]], [[META6]], !".omp_outlined.: %dotcopy_fn."}
// CK1-32: [[META11]] = !{[[META12:![0-9]+]]}
// CK1-32: [[META12]] = distinct !{[[META12]], [[META6]], !".omp_outlined.: %__context"}
// CK1-32: [[META13]] = !{[[META5]], [[META8]], [[META10]], [[META12]]}
// CK1-32: [[META14]] = !{[[META15:![0-9]+]]}
// CK1-32: [[META15]] = distinct !{[[META15]], [[META16:![0-9]+]], !".omp_outlined..3: %dotpart_id."}
// CK1-32: [[META16]] = distinct !{[[META16]], !".omp_outlined..3"}
// CK1-32: [[META17]] = !{[[META18:![0-9]+]]}
// CK1-32: [[META18]] = distinct !{[[META18]], [[META16]], !".omp_outlined..3: %dotprivates."}
// CK1-32: [[META19]] = !{[[META20:![0-9]+]]}
// CK1-32: [[META20]] = distinct !{[[META20]], [[META16]], !".omp_outlined..3: %dotcopy_fn."}
// CK1-32: [[META21]] = !{[[META22:![0-9]+]]}
// CK1-32: [[META22]] = distinct !{[[META22]], [[META16]], !".omp_outlined..3: %__context"}
// CK1-32: [[META23]] = !{[[META15]], [[META18]], [[META20]], [[META22]]}
// CK1-32: [[META24]] = !{[[META25:![0-9]+]]}
// CK1-32: [[META25]] = distinct !{[[META25]], [[META26:![0-9]+]], !".omp_outlined..7: %dotpart_id."}
// CK1-32: [[META26]] = distinct !{[[META26]], !".omp_outlined..7"}
// CK1-32: [[META27]] = !{[[META28:![0-9]+]]}
// CK1-32: [[META28]] = distinct !{[[META28]], [[META26]], !".omp_outlined..7: %dotprivates."}
// CK1-32: [[META29]] = !{[[META30:![0-9]+]]}
// CK1-32: [[META30]] = distinct !{[[META30]], [[META26]], !".omp_outlined..7: %dotcopy_fn."}
// CK1-32: [[META31]] = !{[[META32:![0-9]+]]}
// CK1-32: [[META32]] = distinct !{[[META32]], [[META26]], !".omp_outlined..7: %__context"}
// CK1-32: [[META33]] = !{[[META25]], [[META28]], [[META30]], [[META32]]}
// CK1-32: [[META34]] = !{[[META35:![0-9]+]]}
// CK1-32: [[META35]] = distinct !{[[META35]], [[META36:![0-9]+]], !".omp_outlined..12: %dotpart_id."}
// CK1-32: [[META36]] = distinct !{[[META36]], !".omp_outlined..12"}
// CK1-32: [[META37]] = !{[[META38:![0-9]+]]}
// CK1-32: [[META38]] = distinct !{[[META38]], [[META36]], !".omp_outlined..12: %dotprivates."}
// CK1-32: [[META39]] = !{[[META40:![0-9]+]]}
// CK1-32: [[META40]] = distinct !{[[META40]], [[META36]], !".omp_outlined..12: %dotcopy_fn."}
// CK1-32: [[META41]] = !{[[META42:![0-9]+]]}
// CK1-32: [[META42]] = distinct !{[[META42]], [[META36]], !".omp_outlined..12: %__context"}
// CK1-32: [[META43]] = !{[[META35]], [[META38]], [[META40]], [[META42]]}
//.
