// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --replace-value-regex "__omp_offloading_[0-9a-z]+_[0-9a-z]+(\w+)_l[0-9]+" "reduction_size[.].+[.]" "pl_cond[.].+[.|,]" --prefix-filecheck-ir-name _ --version 6
// expected-no-diagnostics
#ifndef HEADER
#define HEADER

///==========================================================================///
// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4

// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=45 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=45 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4

// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=50 -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_12-_11-_5-_4,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9
// RUN: %clang_cc1 -DCK10 -verify -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4
// RUN: %clang_cc1 -DCK10 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp -fopenmp-version=50 -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap  %s --check-prefixes=CHECK-CK10-_,CK10,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4

// RUN: %clang_cc1 -DCK10 -verify -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK10-_,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,SIMD-ONLY9-_5-_3 %s
// RUN: %clang_cc1 -DCK10 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -std=c++11 -triple powerpc64le-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=powerpc64le-ibm-linux-gnu -x c++ -triple powerpc64le-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK10-_,CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,SIMD-ONLY9-_5-_3 %s
// RUN: %clang_cc1 -DCK10 -verify -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -emit-llvm %s -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK10-_,CK10-_13-_9-_2-_7-_12-_11-_10-_6-_5-_4-_8-_3-SIMD-ONLY9,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4,SIMD-ONLY9-_2-_4 %s
// RUN: %clang_cc1 -DCK10 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -std=c++11 -triple i386-unknown-unknown -emit-pch -o %t %s
// RUN: %clang_cc1 -fopenmp-simd -fopenmp-targets=i386-pc-linux-gnu -x c++ -triple i386-unknown-unknown -std=c++11 -include-pch %t -verify %s -emit-llvm -o - | FileCheck -allow-deprecated-dag-overlap --check-prefixes=CHECK-CK10-_,CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4,SIMD-ONLY9-_2-_4 %s
#ifdef CK10


// Map types: OMP_MAP_TARGET_PARAM | OMP_MAP_IMPLICIT = 544

void implicit_maps_pointer (){
  double *ddyn;


#pragma omp target
  {
    ddyn[0] += 1.0;
    ddyn[1] += 1.0;
  }
}


#endif // CK10
#endif
// CHECK-CK10-_-LABEL: define dso_local void @_Z21implicit_maps_pointerv(
// CHECK-CK10-_-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-CK10-_-NEXT:  [[ENTRY:.*:]]
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[DDYN:%.*]] = alloca ptr, align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[DDYN:%.*]] = alloca ptr, align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[DOTOFFLOAD_BASEPTRS:%.*]] = alloca [1 x ptr], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[DOTOFFLOAD_PTRS:%.*]] = alloca [1 x ptr], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[DOTOFFLOAD_MAPPERS:%.*]] = alloca [1 x ptr], align 4
// CK10-NEXT:    [[KERNEL_ARGS:%.*]] = alloca [[STRUCT___TGT_KERNEL_ARGUMENTS:%.*]], align 8
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DDYN]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DDYN]], align 4
// CK10-NEXT:    [[TMP1:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_BASEPTRS]], i32 0, i32 0
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 4
// CK10-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_PTRS]], i32 0, i32 0
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i64 0, i64 0
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr null, ptr [[TMP3]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [1 x ptr], ptr [[DOTOFFLOAD_MAPPERS]], i32 0, i32 0
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr null, ptr [[TMP3]], align 4
// CK10-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 0
// CK10-NEXT:    store i32 3, ptr [[TMP4]], align 4
// CK10-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 1
// CK10-NEXT:    store i32 1, ptr [[TMP5]], align 4
// CK10-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 2
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS]], ptr [[TMP6]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr [[DOTOFFLOAD_BASEPTRS]], ptr [[TMP6]], align 4
// CK10-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 3
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr [[DOTOFFLOAD_PTRS]], ptr [[TMP7]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr [[DOTOFFLOAD_PTRS]], ptr [[TMP7]], align 4
// CK10-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 4
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr @.offload_sizes, ptr [[TMP8]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr @.offload_sizes, ptr [[TMP8]], align 4
// CK10-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 5
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr @.offload_maptypes, ptr [[TMP9]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr @.offload_maptypes, ptr [[TMP9]], align 4
// CK10-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 6
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr null, ptr [[TMP10]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr null, ptr [[TMP10]], align 4
// CK10-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 7
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr null, ptr [[TMP11]], align 8
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr null, ptr [[TMP11]], align 4
// CK10-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 8
// CK10-NEXT:    store i64 0, ptr [[TMP12]], align 8
// CK10-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 9
// CK10-NEXT:    store i64 0, ptr [[TMP13]], align 8
// CK10-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 10
// CK10-NEXT:    store [3 x i32] [i32 -1, i32 0, i32 0], ptr [[TMP14]], align 4
// CK10-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 11
// CK10-NEXT:    store [3 x i32] zeroinitializer, ptr [[TMP15]], align 4
// CK10-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw [[STRUCT___TGT_KERNEL_ARGUMENTS]], ptr [[KERNEL_ARGS]], i32 0, i32 12
// CK10-NEXT:    store i32 0, ptr [[TMP16]], align 4
// CK10-NEXT:    [[TMP17:%.*]] = call i32 @__tgt_target_kernel(ptr @[[GLOB1:[0-9]+]], i64 -1, i32 -1, i32 0, ptr @.{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z21implicit_maps_pointerv_l[0-9]+}}.region_id, ptr [[KERNEL_ARGS]])
// CK10-NEXT:    [[TMP18:%.*]] = icmp ne i32 [[TMP17]], 0
// CK10-NEXT:    br i1 [[TMP18]], label %[[OMP_OFFLOAD_FAILED:.*]], label %[[OMP_OFFLOAD_CONT:.*]]
// CK10:       [[OMP_OFFLOAD_FAILED]]:
// CK10-NEXT:    call void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z21implicit_maps_pointerv_l[0-9]+}}(ptr [[TMP0]]) #[[ATTR2:[0-9]+]]
// CK10-NEXT:    br label %[[OMP_OFFLOAD_CONT]]
// CK10:       [[OMP_OFFLOAD_CONT]]:
// CK10-NEXT:    ret void
//
//
// CK10-LABEL: define internal void @{{__omp_offloading_[0-9a-z]+_[0-9a-z]+__Z21implicit_maps_pointerv_l[0-9]+}}(
// CK10-SAME: ptr noundef [[DDYN:%.*]]) #[[ATTR1:[0-9]+]] {
// CK10-NEXT:  [[ENTRY:.*:]]
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[DDYN_ADDR:%.*]] = alloca ptr, align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    store ptr [[DDYN]], ptr [[DDYN_ADDR]], align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DDYN_ADDR]], align 8
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds double, ptr [[TMP0]], i64 0
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[TMP1:%.*]] = load double, ptr [[ARRAYIDX]], align 8
// SIMD-ONLY9-_2-_4-NEXT:    [[DDYN:%.*]] = alloca ptr, align 4
// SIMD-ONLY9-_2-_4-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DDYN]], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[DDYN_ADDR:%.*]] = alloca ptr, align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    store ptr [[DDYN]], ptr [[DDYN_ADDR]], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[DDYN_ADDR]], align 4
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds double, ptr [[TMP0]], i32 0
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    [[TMP1:%.*]] = load double, ptr [[ARRAYIDX]], align 4
// CHECK-CK10-_-NEXT:    [[ADD:%.*]] = fadd double [[TMP1]], 1.000000e+00
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    store double [[ADD]], ptr [[ARRAYIDX]], align 8
// SIMD-ONLY9-_5-_3-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DDYN]], align 8
// CK10-_13-_9-_12-_11-_5-_4-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DDYN_ADDR]], align 8
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[TMP2]], i64 1
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    [[TMP3:%.*]] = load double, ptr [[ARRAYIDX1]], align 8
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    store double [[ADD]], ptr [[ARRAYIDX]], align 4
// SIMD-ONLY9-_2-_4-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DDYN]], align 4
// CK10-_2-_7-_10-_6-_8-_3-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DDYN_ADDR]], align 4
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds double, ptr [[TMP2]], i32 1
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    [[TMP3:%.*]] = load double, ptr [[ARRAYIDX1]], align 4
// CHECK-CK10-_-NEXT:    [[ADD2:%.*]] = fadd double [[TMP3]], 1.000000e+00
// CK10-_13-_9-_12-_11-_5-_4-SIMD-ONLY9-_3-NEXT:    store double [[ADD2]], ptr [[ARRAYIDX1]], align 8
// CK10-_2-_7-_10-_6-_8-_3-SIMD-ONLY9-_4-NEXT:    store double [[ADD2]], ptr [[ARRAYIDX1]], align 4
// CHECK-CK10-_-NEXT:    ret void
//
//
